services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
     - dbdata:/var/lib/mysql
    networks:
     - app-network
  flaskapp:
    build:
     context: .
    depends_on:
      mysql:
        condition: service_healthy
    container_name: flaskapp
    restart: unless-stopped
    volumes:
     - ./config/db_config.py:/app/config/db_config.py
    networks:
     - app-network
  caddy:
    image: caddy:2.10.0-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
     - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
